version: "3.8"
services:
  usermanager-app:
    image: "styx1291/usermanager:latest"
    container_name: "usermanager-app1"
    ports:
      - "8082:8080"
    networks:
      - "user-management-app"
    depends_on:
      mysql-db:
        condition: service_healthy
  mysql-db:
    image: "styx1291/usermanager:mysql-db"
    container_name: "mysql-remote"
    networks:
      - "user-management-app"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: mysqladmin -uroot -proot ping
      interval: 2s
      timeout: 5s
      retries: 30
networks:
  user-management-app: